### ISSUE TITLE
SDNS stamp can not be parsed anymore

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#183]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

SDNS stamp can not be parsed anymore:
sdns://AgEAAAAAAAAADTgyLjE0Ni40Mi4yMTMADWRucy5hbW1udC5hcHAOL2Rucy1xdWVyeS9pZDE

![image](https://user-images.githubusercontent.com/45385632/209208061-44e439a9-e2bd-4714-b99a-049b6ca76c46.png)

I had to roll back to version 1.2.3 to configure secure DNS, then upgrade again🤷🏻‍♂️

- **AdGuard VPN version:**
  - 2.0.0.279
- **Operating system and version:**
  - macOS 13.1
- **Other network-level software:**
  - AdGuard 2.9.1.1217 release

**Comment by maxikuzmin** [comment]
@ammnt I don't have this problem. Are you still having this recurring?

**Comment by ammnt** [comment]
@maxikuzmin, yes, of course. Nothing changed🤷🏻‍♂️

**Comment by maxikuzmin** [comment]
@ammnt to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by ameshkov** [comment]
@maxikuzmin I don't get it, the issue is easily reproduced on the stable v2.0, what's the problem?

**Comment by maxikuzmin** [comment]
@ammnt we have taken care of the situation. The [nightly version](https://agrd.io/mac_vpn_nightly) has already fixed this problem. You can download the nightly version for now, we will release the new public version soon
Please let us know your results

**Comment by ammnt** [comment]
Works perfect now! Thank you so much!
