### ISSUE TITLE
Kill Switch fails when connection to DNS lost

### ISSUE THREAD

**Issue by alex-osm** [AdguardTeam/AdGuardVPNForMac#209]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.4.337 beta

### Environment

```markdown
- OS: Ventura 13.2.1
- Other network-level software:
```

### Issue Details

It seems kill-switch fails when app looses connection to DNS server. I use AdGuard DNS over https. I noticed two times already: AdGuard VPN paused with message - Unreachable DNS server address (see screenshot). While the app in this state - kill-switch is not active also, but turned on in settings.

### Expected Behavior

Kill Switch active and block connections

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="640" alt="image" src="https://user-images.githubusercontent.com/74016125/232692691-9c5f3577-932d-47b0-99cc-b44786e900c4.png">

</details>

**Comment by AlexandrPkhm** [comment]
Hi @alex-osm!

Please note that currently the most recent version of AdGuard VPN for macOS is 2.0.5.340 release. Please try to update to this version and let us know if the issue persists.

We will be waiting!

**Comment by alex-osm** [comment]
I have  2.0.5.341 now and bug still persists. I've just noticed that it appears when mac is waking up from sleep.

**Comment by AlexandrPkhm** [comment]
@alex-osm 

Unfortunately, we were unable to reproduce the issue. Could you please record the debug logs and send them to us via [apple@adguard.com](mailto:apple@adguard.com) email address. Don't forget to leave a link to the GitHub issue in the email so we can find your logs. To record the logs, please:

1. Click on the `AdGuard VPN` icon in the [menu bar](https://support.apple.com/guide/mac-help/whats-in-the-menu-bar-mchlp1446/mac) → `Settings` → `App settings` → `Advanced settings`, and set `Logging level` for `Record everything`
2. Reproduce the issue
3. Go to `Advanced` and click on the `Export logs and system info...` button
4. Save the archive, send it to us, and specify the time the issue was reproduced
5. Set the logging level back to `Record by default`, otherwise, the app will keep recording the logs, which will be taking up too much space later on

If it is possible please also provide us with the approximate steps to reproduce the issue.

**Comment by AlexandrPkhm** [comment]
@alex-osm 

Please let us know if there are any news.

**Comment by alex-osm** [comment]
Logs were sent. 
Issue was reproduced today with new 2.1.0.379 beta (at 13:15 approx)
Updated and started app, then pressed Connect button. Alert appeared and all connections in exclusions go to provider instead of VPN. After I switched from Custom AdGuard DNS (https) to the default AdGuard DNS server, the issue disappeared.

**Comment by AlexandrPkhm** [comment]
@alex-osm Unfortunately, we do not seem to have received your logs. Could you please resend them to us.

**Comment by AlexandrPkhm** [comment]
@alex-osm We have indeed received your logs and will continue to investigate. We will contact you as soon as we have any information on this issue.

**Comment by alex-osm** [comment]
Thank you! Looks like this issue is gone. 
However I noticed other issue today - huge memory consumption (around of 2 GB) with 2.1.0.400 beta installed. I will observe if it will appear again with nightly.

**Comment by alex-osm** [comment]
<img width="264" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/74016125/da7bf451-ffbf-48ee-b166-5ea2ddfb7b97">

Looks like memory leak (2.1.0.413 nightly)
